name: Terraform Deployment
on:
  push:
    branches:
      - main
  workflow_dispatch:  # Allow manual trigger for apply job

env:
  PROJECT_ID: hijra-440311
  COMPUTE_ZONE: asia-south2
  
jobs:
  terraform_plan:
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - id: 'auth'
        name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v0.4.0
        with:
          credentials_json: '${{ secrets.CREDENTIALS_JSON }}'

      - name: Set up Google Cloud SDK
        uses: 'google-github-actions/setup-gcloud@v1'
        with:
          project_id: ${{ env.PROJECT_ID }}

      - name: Configure Google Cloud
        run: |
          echo "Project ID: ${{ env.PROJECT_ID }}"
          echo "Compute Zone: ${{ env.COMPUTE_ZONE }}"
          gcloud config set project ${{ env.PROJECT_ID }}
          gcloud config set compute/zone ${{ env.COMPUTE_ZONE }}

      - name: Initialize Terraform
        run: |
          cd terraform  # Berpindah ke direktori terraform
          terraform init

      - name: Validate Terraform configuration
        run: |
          cd terraform  # Pastikan berada di direktori terraform
          terraform validate

      - name: Plan Terraform deployment
        run: |
          cd terraform  # Berpindah ke direktori terraform
          terraform plan -out=tfplan -lock=false

  terraform_apply:
    runs-on: ubuntu-latest
    needs: terraform_plan
    if: github.event_name == 'workflow_dispatch'  # Only run on manual trigger
    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - id: 'auth'
        name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v0.4.0
        with:
          credentials_json: '${{ secrets.CREDENTIALS_JSON }}'

      - name: Set up Google Cloud SDK
        uses: 'google-github-actions/setup-gcloud@v1'
        with:
          project_id: ${{ env.PROJECT_ID }}

      - name: Configure Google Cloud
        run: |
          echo "Project ID: ${{ env.PROJECT_ID }}"
          echo "Compute Zone: ${{ env.COMPUTE_ZONE }}"
          gcloud config set project ${{ env.PROJECT_ID }}
          gcloud config set compute/zone ${{ env.COMPUTE_ZONE }}

      - name: Apply Terraform changes
        run: |
          cd terraform  # Change to the terraform directory
          terraform apply -auto-approve 

  ansible_deploy:
      runs-on: ubuntu-latest
      needs: terraform_apply
      if: github.event_name == 'workflow_dispatch'  # Only run on manual trigger
      permissions:
        contents: 'read'
        id-token: 'write'

      steps:
        - name: Checkout repository
          uses: actions/checkout@v3

        - id: 'auth'
          name: Authenticate to Google Cloud
          uses: google-github-actions/auth@v0.4.0
          with:
            credentials_json: '${{ secrets.CREDENTIALS_JSON }}' 

        - name: Install Ansible
          run: |
            sudo apt-get update
            sudo apt-get install -y ansible

        - name: Configure Ansible inventory
          run: |
            echo "[my_servers]" > inventory.ini
            echo "${{ steps.terraform.outputs.instance_ip }}" >> inventory.ini

        - name: Run Ansible Playbook
          run: ansible-playbook -i inventory.ini install_docker.yml